os: Windows Server 2012

environment:
  matrix:
    - TOXENV: py37
    - TOXENV: py38

install:
  - C:\Python37\python -m pip install -U -r test-requirements.txt

test_script:
  - C:\Python37\scripts\tox

build: off