name: PR-Merge

on:
  push:
    branches:
      - 'master'

jobs:

  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml

  publish-docs:
    name: Publish Documentation
    uses: ./.github/workflows/gh-pages.yml